### ISSUE TITLE
Southern hemisphere sun position

### ISSUE THREAD

**Issue by derek049** [kshetline/prague-clock#26]
Hi, I am new to this so please excuse wrong formats, protocols etc.

I am fascinated by the Prague clock and it's simulation, it is a beautiful piece of work

The issue that I think exists is the position of the sun when the latitude is the southern hemisphere. It is currently shown towards the outside edges of the clock, indicating long days and short nights, while in December it is closer to the middle, showing short nights and long days. Of course the southern hemisphere is the opposite of this.  This leads to the sunset and sunrise times not showing correctly as the sun passes into the red and black zones.

Am I reading something wrong? or can it be fixed?

Regards

Derek

**Comment by kshetline** [comment]
I think you've got a point there. I copied the southern hemisphere treatment from the same place I got the original SVG graphics (https://drifted.in/horologium-app/), but hadn't considered what that implied about the position of the sun.

Hmmm... now I've got to think about what changes are really needed!

**Comment by derek049** [comment]
Sorry to give you work to do, but about half the world will appreciate it very much :)

Regards
Derek

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by kshetline** [comment]
No problem! It's an interesting puzzle. One possible approach is to never flip the display at all for the southern hemisphere, but just let the hour lines arc upward after you cross the equator, in a smooth flow with the way you see the lines change as you adjust latitude from the north closer and close to the equator.

That would put the sky at the bottom for the southern hemisphere, however, which is weird. Also, while some people might find it strange that (as currently designed) the hands of the clock go counterclockwise in the southern hemisphere, what we call "counterclockwise" in our northern-hemisphere dominated language is "clockwise" for a southern hemisphere sundial.

I think the solution I prefer, if I keep the sky on the top for everyone, is to flip the ecliptic wheel top-to-bottom, and then I think I need to rearrange the zodiac symbols so that Aries through Virgo are in the squished section of the wheel, and Libra-Pisces are in the spread-out section.

**Comment by derek049** [comment]
Yes I think it would be weird having the sky at the bottom. All I can do is wish you good luck! I really look forward to the final outcome

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by kshetline** [comment]
I haven't deployed any changes on the main website, but here's a test version of the changes: https://test.shetline.com/orloj/

Does that work better for the results you were expecting?

**Comment by derek049** [comment]
Yes it seems to be correct now, beautiful, thank you

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by kshetline** [comment]
I found a little more to be adjusted for the southern hemisphere mode, did some more testing, and have now released the changes to the main site.
